.PHONY: all clean cleanall

all:
	$(MAKE) -C TinyPTC
	$(MAKE) -C picoPNG

clean:
	$(MAKE) -C TinyPTC clean
	$(MAKE) -C picoPNG clean

cleanall:
	$(MAKE) -C TinyPTC cleanall
	$(MAKE) -C picoPNG cleanall